config/routes.rb
Rails.application.routes.draw do
  
  resources :data
  root  'static_pages#home'
  match '/home' , to: 'static_pages#home', via: 'get'
  match '/aboutus' , to: 'static_pages#aboutus', via: 'get'
  match '/admissions' , to: 'static_pages#admissions', via: 'get'
  match '/academics' , to: 'static_pages#academics', via: 'get'
  match '/student' , to: 'static_pages#student', via: 'get'
  match '/accreditation' , to: 'static_pages#accreditation', via: 'get'
  match '/apply' , to: 'static_pages#apply', via: 'get'
  match '/fourbigtips' , to: 'static_pages#fourbigtips', via: 'get'
   match '/thankyou' , to: 'static_pages#thankyou', via: 'get'

end

app/models/datum.rb
class Datum < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  before_action :set_datum, only: [:show, :edit, :update, :destroy]

  # GET /data
  # GET /data.json
  def index
    @data = Datum.all
  end

  # GET /data/1
  # GET /data/1.json
  def show
  end

  # GET /data/new
  def new
    @datum = Datum.new
  end

  # GET /data/1/edit
  def edit
  end

  # POST /data
  # POST /data.json
  def create
    @datum = Datum.new(datum_params)

    respond_to do |format|
      if @datum.save
        format.html { redirect_to '/thankyou' }
        format.json { render :show, status: :created, location: @datum }
      else
        format.html { render :new }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data/1
  # PATCH/PUT /data/1.json
  def update
    respond_to do |format|
      if @datum.update(datum_params)
        format.html { redirect_to @datum, notice: 'Datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @datum }
      else
        format.html { render :edit }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1
  # DELETE /data/1.json
  def destroy
    @datum.destroy
    respond_to do |format|
      format.html { redirect_to data_url, notice: 'Datum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datum
      @datum = Datum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datum_params
      params.require(:datum).permit(:name, :email, :phone, :message)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

def home
  @datum = Datum.new
end 

def aboutus
  @datum = Datum.new
end

def admissions
  @datum = Datum.new
end

def academics
  @datum = Datum.new
end

def student
  @datum = Datum.new
end

def accreditation
  @datum = Datum.new
end

def apply
   @datum = Datum.new
end 

def fourbigtips
   @datum = Datum.new
end

def thankyou
   @datum = Datum.new
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/views/data/_form.html.erb
<%= form_for(@datum) do |f| %>
  <% if @datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
      <% @datum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<p class="center-align" style="font-weight: bold; color: rgb(33, 150, 243);">Tell us a little about you. What are your dreams??</p>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label "What are your dreams" %><br>
    <%= f.text_area :message, :class => "apply-textarea" %>
  </div>
  <div class="actions">
    <%= f.submit "Send", class: "btn sbcolor" , :style => "background-color: #ddd; color: #000;" %>
  </div>
<% end %>

app/views/data/edit.html.erb
<h1>Editing Datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @datum %> |
<%= link_to 'Back', data_path %>

app/views/data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Data</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data.each do |datum| %>
      <tr>
        <td><%= datum.name %></td>
        <td><%= datum.email %></td>
        <td><%= datum.phone %></td>
        <td><%= datum.message %></td>
        <td><%= link_to 'Show', datum %></td>
        <td><%= link_to 'Edit', edit_datum_path(datum) %></td>
        <td><%= link_to 'Destroy', datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Datum', new_datum_path %>

app/views/data/new.html.erb
<h1>New Datum</h1>

<%= render 'form' %>

<%= link_to 'Back', data_path %>

app/views/data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @datum.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @datum.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @datum.phone %>
</p>

<p>
  <strong>Message:</strong>
  <%= @datum.message %>
</p>

<%= link_to 'Edit', edit_datum_path(@datum) %> |
<%= link_to 'Back', data_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Purity Technology Institute </title>
 
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/aboutus.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
      <link href="https://fonts.googleapis.com/css?family=Courgette" rel="stylesheet">
      <link type="text/css" rel="stylesheet" href="css/slick.css"  media="screen,projection"/>
      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

<style>

nav {
  color: #fff;
  background-color: #ee6e73;
  width: 100%;
  height: 66px;
  line-height: 56px;

}

nav .centim {
  margin-left: 25%;

}

.activelink{
  border-bottom: 5px solid #4da2d9;
  color: black;
}

nav ul a {
  transition: background-color .3s;
  font-size: 14px;
  color: black;
  display: inline-block;
  padding: 0 15px;
  cursor: pointer;
}

 .oclass{
    color: #8c8c8c;
    text-transform: capitalize;
   }


   .navhov:hover{
 border-bottom: 5px solid #ddd;
 color: #42ade7; 
 background: white;
}




.navhovactive{
  border-bottom: 5px solid #4da2d9;
  color: black;
 background: white;
 font-weight: bold;
}

   .logomenu{
    height: 100%;
    margin-left: 20px;
   }

.gateman{
  margin-right: 50px;
}

.aboutimage{
  width: 100%;
  height: 350px;
  z-index: -2;
  position: relative;
  top: -20px;
}

.aboutindex{
  width: 100%;
  height: auto;
  background-color: #8bbad5;
  padding: 15px;
}

.creative{
    font-size: 20px;
   font-weight: 300;
   line-height: 35px;
   color: #363637;
   text-align: justify;
   text-justify: inter-word;
}


input[type=email] {
  line-height: 12px;
  height: 40px;
  padding-left: 2rem;
  background-color: #fff;
  border-radius: 25px 25px 25px 25px;
  width: 200px;
   }
   input[type=email]:focus {
    background-color: #fff;
    border-radius: 25px 25px 25px 25px;
    box-shadow: none;
    color: #444; }
    .input-field input[type=email]:focus + label i, .input-field input[type=text]:focus ~ .mdi-navigation-close {
      color: #444; }
  .input-field input[type=email] + label {
    left: 1rem; }
  .input-field input[type=email] ~ .mdi-navigation-close {
    position: relative;
    top: 0;
    right: 1rem;
    color: transparent;
    cursor: pointer;
    font-size: 2rem;
   }

   input[type=text] {
  line-height: 12px;
  height: 40px;
  padding-left: 2rem;
  background-color: #fff;
  border-radius: 25px 25px 25px 25px;
  width: 200px;
 }
   input[type=text]:focus {
    background-color: #fff;
    border-radius: 25px 25px 25px 25px;
    box-shadow: none;
    color: #444; }
    .input-field input[type=text]:focus + label i, .input-field input[type=text]:focus ~ .mdi-navigation-close {
      color: #444; }
  .input-field input[type=text] + label {
    left: 1rem; }
  .input-field input[type=text] ~ .mdi-navigation-close {
    position: relative;
    top: 0;
    right: 1rem;
    color: transparent;
    cursor: pointer;
    font-size: 2rem;
   }

::-webkit-input-placeholder {
 font-size: 15px;
 color: #d0cdfa;
}

   .ymesag{
    height: 100px;
    padding: 20px;
     background-color: #fff;
  border-radius: 25px 25px 25px 25px;
  width: 100%;
   }

   .collection {
  margin: 0.5rem 0 1rem 0;
  border-radius: 2px;
  overflow: hidden;
  position: relative;
  border: 1px solid #4da2d9;
}

.collection .collection-item {
  background-color: #4da2d9;
  line-height: 1.5rem;
  padding: 10px 20px;
  height: auto;
  margin: 7px;
  height: auto;
}


.collection .collection-item.avatar .activity{
  padding-top: 0px;
    font-size: 15px;
    font-weight: 600;
}

.pitlogo{
  float: right;
  margin-left: 20px;
}

@media only screen and (max-width : 992px) {

 .logomenu{
    height: 100%;
    margin-left: 0px;
   }

.aboutimage{
  width: 100%;
  height: 180px;
  z-index: -2;
  position: relative;
  top: -20px;
}

}

</style>

<body>

  <nav>
 
    <div class="nav-wrapper" style="background-color: white;">
<a href="/" class="brand-logo logomenu hide-on-med-and-down"><img src="logo.png" class="logomenu" ></a>
<a href="/" class="brand-logo logomenu hide-on-large-only"><img src="logomobile.png" class="logomenu" ></a>
<a href="#" data-activates="mobile-demo" class="button-collapse"><i style="color: #ddd;" class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down gateman">
      <li><a href="/"  class="navhov oclass">Home</a></li>
        <li><a href="/aboutus" class="navhov oclass navhovactive">About Us</a></li>
        <li><a href="/admissions" class="navhov oclass">Admissions</a></li>
        <li><a href="/academics" class="navhov oclass">Academics</a></li>
        <li><a href="/student" class="navhov oclass">Student</a></li>
        <li><a href="/accreditation" class="navhov oclass">Accreditation</a></li>
        <li><a href="/apply" class="navhov oclass">Apply</a></li>
      </ul>
        <ul class="side-nav" id="mobile-demo">
        <li><a href="/">Home</a></li>
        <li><a href="/aboutus">About Us</a></li>
        <li><a href="/admissions">Admissions</a></li>
        <li><a href="/academics">Academics</a></li>
        <li><a href="/student">Student</a></li>
        <li><a href="/accreditation">Accreditation</a></li>
        <li><a href="/apply">Apply</a></li>
      </ul>
    </div>
  </nav>

  <div class="row">
    <img src="abtus.jpg" class="resposive-img aboutimage">
  </div>

  <div class="row">
    <div class="container">
      <div class="col l3 hide-on-med-and-down">
        <div class="aboutindex">
          <h5 style="color: white;"> About </h5>
          <ul>
          <li style="font-size: 14px; color: white; font-weight: 700; padding-bottom: 10px; border-bottom: 2px dotted white; margin-bottom: 5px; margin-top: 5px;"> Creativity and innovation</li>
          <li style="font-size: 14px; color: white; font-weight: 700; padding-bottom: 10px; border-bottom: 2px dotted white; margin-bottom: 5px; margin-top: 5px;">Applied Learning</li>
          <li style="font-size: 14px; color: white; font-weight: 700; padding-bottom: 10px; border-bottom: 2px dotted white; margin-bottom: 5px; margin-top: 5px;">Purpose and Mission</li>
          </ul>
        </div>
      </div>
      <div class="col l9">
        <h4 style="color: #42a2d9;">Creativity and innovation</h4>
        <p class="creative">
        <img src="pit.png" width="150px" height="200px" class="pitlogo hide-on-med-and-down">
       At <strong>Purirty Technology Institute</strong>, we believe that a country's growth and progress is tagged to how much it can innovate. Inovation is not only the one factor but in a more intrinsic way, creating that connetion between creativity and innovation. We educate our students with these core values in mind, ensuring it is well engrained in their spirits. Most of our students work work in great institutions and are key to helping shape the creativity and innovation culture in the company. Creativity is key, so is innovation. They cannot live with or without that is why it is fostered strongly in our school.
        </p>
         <h4 style="color: #42a2d9;">Applied Learning</h4>
        <p class="creative">
       Applied learning is very key and pivotal to our curriculum. What is the essense of a technical course if students can't apply it in their work environments. Applied learning places emphasis on practice, less on theory. The two are connected in a wonderful way to ensure productivity in the work environment.
        </p>
         <h4 style="color: #42a2d9;">Our Mission</h4>
        <p class="creative">
       At <strong>Purity</strong>, our vision is to raise a new generation of technicians with an eye for innovation who will create value and Transform Mother Ghana through their participation in the various work environments.
        </p>
      </div>
    </div>
  </div>

<footer class="page-footer" style="background-color: #4da2d9;">
          <div class="container">
            <div class="row">
              <div class="col l4 s12">
                <h5 class="white-text">Find us on Social Media</h5>
                 <ul class="collection">
    <li class="collection-item avatar">
      <a href="https://www.facebook.com/puritytechnologyinstitute/"><img src="fblogo.png" alt="" class="circle"></a>
      <p class="activity">
      <a href="https://www.facebook.com/puritytechnologyinstitute/" style="color: black;"> <span class="titl">Facebook</span></a>         
       </p>
    </li>
     <li class="collection-item avatar">
       <a href="https://twitter.com/PurityTI"><img src="tlogo.png" alt="" class="circle"></a>
      <p class="activity">
      <a href="https://twitter.com/PurityTI" style="color: black;"> <span class="titl">Twitter</span></a>         
       </p>    
     </li>
     <li class="collection-item avatar">
       <a href="https://www.instagram.com/purity_technology_institute/"><img src="ilogo.png" alt="" class="circle"></a>
      <p class="activity">
      <a href="https://www.instagram.com/purity_technology_institute/" style="color: black;"> <span class="titl">Instagram</span></a>         
       </p>
    </li>
  </ul>
              </div>
               <div class="col l4 s12">
                <h5 class="white-text">Contact Details</h5>
                <p class="grey-text text-lighten-4">Purity Technology Institute,</p>
                <p class="grey-text text-lighten-4">P.O.Box HP 524, Ho,</p>
                <p class="grey-text text-lighten-4">Ho, Volta Region.</p>
                <p class="grey-text text-lighten-4">0244852432 / 0240417967</p>
              </div>
              <div class="col l4 s12">
                <h5 class="white-text">Contact Us</h5>
                  <%= form_for(@datum) do |f| %>
                <p class="center-align"><input type="text" class="validate"  name="datum[name]" id="datum_name" placeholder="Your name"></p>
                <p class="center-align"><input type="email" class="validate" name="datum[email]" id="datum_email" placeholder="Your email"></p>
                <p class="center-align"><input type="text" class="validate"  name="datum[phone]" id="datum_phone" placeholder="Phone number"></p>
                 <p class="center-align"><textarea class="ymesag" name="datum[message]" id="datum_message" placeholder="Your message here"></textarea></p>
                 <p class="center-align"><input type="submit" name="commit" value="Send" class="btn sbcolor" style="background-color: #fff; color: #000;" /></p>
               <% end %>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            &copy; 2016 Purity Technology Institute. All Rights Reserved.
            <a class="grey-text text-lighten-4 right" href="#!">FAQ</a>
            </div>
          </div>
        </footer>
 <script type="text/javascript" src="jquery.js"></script>
  <script src="js/jquery.slides.min.js"></script>
      <script type="text/javascript" src="js/materialize.min.js"></script>
      <script type="text/javascript">
       $(".button-collapse").sideNav();
      </script>
  </body>
  </html>

app/views/static_pages/accreditation.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
      <link href="https://fonts.googleapis.com/css?family=Courgette" rel="stylesheet">
      <link type="text/css" rel="stylesheet" href="css/slick.css"  media="screen,projection"/>
      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

<style>

nav {
  color: #fff;
  background-color: #ee6e73;
  width: 100%;
  height: 66px;
  line-height: 56px;

}

nav .centim {
  margin-left: 25%;

}

nav ul a {
  transition: background-color .3s;
  font-size: 14px;
  color: black;
  display: inline-block;
  padding: 0 15px;
  cursor: pointer;
}

 .oclass{
    color: #8c8c8c;
    text-transform: capitalize;
   }


   .navhov:hover{
 border-bottom: 5px solid #ddd;
 color: #42ade7; 
 background: white;
}




.navhovactive{
  border-bottom: 5px solid #4da2d9;
  color: black;
 background: white;
 font-weight: bold;
}

   .logomenu{
    height: 100%;
    margin-left: 20px;
   }

.gateman{
  margin-right: 50px;
}

.aboutimage{
  width: 100%;
  height: 350px;
  z-index: -2;
  position: relative;
  top: -20px;
}

.aboutindex{
  width: 100%;
  height: auto;
  background-color: #8bbad5;
  padding: 15px;
}

.creative{
    font-size: 20px;
   font-weight: 300;
   line-height: 35px;
   color: #363637;
   text-align: justify;
   text-justify: inter-word;
}

input[type=email] {
  line-height: 12px;
  height: 40px;
  padding-left: 2rem;
  background-color: #fff;
  border-radius: 25px 25px 25px 25px;
  width: 200px;
   }
   input[type=email]:focus {
    background-color: #fff;
    border-radius: 25px 25px 25px 25px;
    box-shadow: none;
    color: #444; }
    .input-field input[type=email]:focus + label i, .input-field input[type=text]:focus ~ .mdi-navigation-close {
      color: #444; }
  .input-field input[type=email] + label {
    left: 1rem; }
  .input-field input[type=email] ~ .mdi-navigation-close {
    position: relative;
    top: 0;
    right: 1rem;
    color: transparent;
    cursor: pointer;
    font-size: 2rem;
   }

   input[type=text] {
  line-height: 12px;
  height: 40px;
  padding-left: 2rem;
  background-color: #fff;
  border-radius: 25px 25px 25px 25px;
  width: 200px;
 }
   input[type=text]:focus {
    background-color: #fff;
    border-radius: 25px 25px 25px 25px;
    box-shadow: none;
    color: #444; }
    .input-field input[type=text]:focus + label i, .input-field input[type=text]:focus ~ .mdi-navigation-close {
      color: #444; }
  .input-field input[type=text] + label {
    left: 1rem; }
  .input-field input[type=text] ~ .mdi-navigation-close {
    position: relative;
    top: 0;
    right: 1rem;
    color: transparent;
    cursor: pointer;
    font-size: 2rem;
   }

::-webkit-input-placeholder {
 font-size: 15px;
 color: #d0cdfa;
}

   .ymesag{
    height: 100px;
    padding: 20px;
     background-color: #fff;
  border-radius: 25px 25px 25px 25px;
  width: 100%;
   }

   .collection {
  margin: 0.5rem 0 1rem 0;
  border-radius: 2px;
  overflow: hidden;
  position: relative;
  border: 1px solid #4da2d9;
}

.collection .collection-item {
  background-color: #4da2d9;
  line-height: 1.5rem;
  padding: 10px 20px;
  height: auto;
  margin: 7px;
  height: auto;
}


.collection .collection-item.avatar .activity{
  padding-top: 0px;
    font-size: 15px;
    font-weight: 600;
}

.accreditationlogo{
  box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
}

@media only screen and (max-width : 992px) {

 .logomenu{
    height: 100%;
    margin-left: 0px;
   }

.aboutimage{
  width: 100%;
  height: 180px;
  z-index: -2;
  position: relative;
  top: -20px;
}

}

</style>

<body>

  <nav>
 
    <div class="nav-wrapper" style="background-color: white;">
<a href="/" class="brand-logo logomenu hide-on-med-and-down"><img src="logo.png" class="logomenu" ></a>
<a href="/" class="brand-logo logomenu hide-on-large-only"><img src="logomobile.png" class="logomenu" ></a>
<a href="#" data-activates="mobile-demo" class="button-collapse"><i style="color: #ddd;" class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down gateman">
        <li><a href="/"  class="navhov oclass">Home</a></li>
        <li><a href="/aboutus" class="navhov oclass">About Us</a></li>
        <li><a href="/admissions" class="navhov oclass">Admissions</a></li>
        <li><a href="/academics" class="navhov oclass">Academics</a></li>
        <li><a href="/student" class="navhov oclass">Student</a></li>
        <li><a href="/accreditation" class="navhov oclass navhovactive">Accreditation</a></li>
        <li><a href="/apply" class="navhov oclass">Apply</a></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="/">Home</a></li>
        <li><a href="/aboutus">About Us</a></li>
        <li><a href="/admissions">Admissions</a></li>
        <li><a href="/academics">Academics</a></li>
        <li><a href="/student">Student</a></li>
        <li><a href="/accreditation">Accreditation</a></li>
        <li><a href="/apply">Apply</a></li>
      </ul>
    </div>
  </nav>

  <div class="row">
    <img src="acred.jpg" class="resposive-img aboutimage">
  </div>

  <div class="row">
    <div class="container">
      <div class="col l3">
        <img src="geslogo1.png" class="resposive-img accreditationlogo">
      </div>
      <div class="col l9">
        <h5 style="color: #42a2d9;">Ghana Education Service (Technical Education Unit)</h5>
        <p class="creative">
       The Ghana Educational Service Technical Education Unit is an arm of GES responsible for overseeing all technical instituion in Ghana. It's role is to provide accreditation, monitor and make sure technical institutions are living up to their standards.
        </p>
      </div>
      <div class="col l3">
        <img src="moe.jpg" class="resposive-img accreditationlogo" width="100%">
      </div>
      <div class="col l9">
        <h5 style="color: #42a2d9;">Ministry of Education (MOE)</h5>
        <p class="creative">
      The Ministry of Education is committed to put in place an education system focused on promoting creativity and problem-solving through the development of academics, technical and vocational programmes that will improve the acquisition of skills and assure job-market readiness.
        </p>
      </div>
    </div>
  </div>

<footer class="page-footer" style="background-color: #4da2d9;">
          <div class="container">
            <div class="row">
              <div class="col l4 s12">
                <h5 class="white-text">Find us on Social Media</h5>
                              <ul class="collection">
    <li class="collection-item avatar">
      <a href="https://www.facebook.com/puritytechnologyinstitute/"><img src="fblogo.png" alt="" class="circle"></a>
      <p class="activity">
      <a href="https://www.facebook.com/puritytechnologyinstitute/" style="color: black;"> <span class="titl">Facebook</span></a>         
       </p>
    </li>
     <li class="collection-item avatar">
       <a href="https://twitter.com/PurityTI"><img src="tlogo.png" alt="" class="circle"></a>
      <p class="activity">
      <a href="https://twitter.com/PurityTI" style="color: black;"> <span class="titl">Twitter</span></a>         
       </p>    
     </li>
     <li class="collection-item avatar">
       <a href="https://www.instagram.com/purity_technology_institute/"><img src="ilogo.png" alt="" class="circle"></a>
      <p class="activity">
      <a href="https://www.instagram.com/purity_technology_institute/" style="color: black;"> <span class="titl">Instagram</span></a>         
       </p>
    </li>
  </ul>
              </div>
               <div class="col l4 s12">
                <h5 class="white-text">Contact Details</h5>
                <p class="grey-text text-lighten-4">Purity Institute of Technology,</p>
                <p class="grey-text text-lighten-4">P.O.Box HP 524, Ho,</p>
                <p class="grey-text text-lighten-4">Ho, Volta Region.</p>
                <p class="grey-text text-lighten-4">0244852432 / 0240417967</p>
              </div>
              <div class="col l4 s12">
                <h5 class="white-text">Contact Us</h5>
                  <%= form_for(@datum) do |f| %>
                <p class="center-align"><input type="text" class="validate"  name="datum[name]" id="datum_name" placeholder="Your name"></p>
                <p class="center-align"><input type="email" class="validate" name="datum[email]" id="datum_email" placeholder="Your email"></p>
                <p class="center-align"><input type="text" class="validate"  name="datum[phone]" id="datum_phone" placeholder="Phone number"></p>
                 <p class="center-align"><textarea class="ymesag" name="datum[message]" id="datum_message" placeholder="Your message here"></textarea></p>
                 <p class="center-align"><input type="submit" name="commit" value="Send" class="btn sbcolor" style="background-color: #fff; color: #000;" /></p>
               <% end %>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            &copy; 2016 Purity Institute of Technology. All Rights Reserved.
            <a class="grey-text text-lighten-4 right" href="#!">FAQ</a>
            </div>
          </div>
        </footer>
 <script type="text/javascript" src="jquery.js"></script>
  <script src="js/jquery.slides.min.js"></script>
      <script type="text/javascript" src="js/materialize.min.js"></script>
      <script type="text/javascript">
       $(".button-collapse").sideNav();
      </script>
  </body>
  </html>

app/views/static_pages/thankyou.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
      <link href="https://fonts.googleapis.com/css?family=Courgette" rel="stylesheet">
      <link type="text/css" rel="stylesheet" href="css/slick.css"  media="screen,projection"/>
      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <style type="text/css">
     .mematic{
      color: #1aa8ea;
      font-weight: bolder;
     }
    </style>

    <body style="background-color: #fefefe;">
    <div class="container">
    <br>
    <br>
    <h1 class="center-align mematic">Thank You!</h1>
    <p class="center-align thankp">Thanks for getting to us. We will get back to you soon. We wish you the best!</p>

    <p class="center-align"><a href="/">Return to our home page</a> | <a href="/aboutus">Know more about us</a> | <a href="/academics"> Courses offered</a>
    </div>

    <script type="text/javascript" src="jquery.js"></script>
  <script src="js/jquery.slides.min.js"></script>
      <script type="text/javascript" src="js/materialize.min.js"></script>
      <script type="text/javascript">
       $(".button-collapse").sideNav();
      </script>
    
  </body>
  </html>